# Generated by Django 5.1.6 on 2025-02-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('subscribers_number', models.PositiveBigIntegerField(default=0, verbose_name='登録者数')),
            ],
        ),
    ]
