# Generated by Django 5.1.6 on 2025-02-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='Channel_name',
            new_name='channel_name',
        ),
    ]
