# Generated by Django 5.1.6 on 2025-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
