# Generated by Django 5.1.6 on 2025-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_video_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='like'),
        ),
    ]
