# Generated by Django 5.1.6 on 2025-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, unique=True),
        ),
    ]
