# Generated by Django 5.1.6 on 2025-03-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='discription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='likes'),
        ),
    ]
