# Generated by Django 5.1.6 on 2025-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_alter_video_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='discription',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
