# Generated by Django 5.1.6 on 2025-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0016_alter_video_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='like_count'),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='view_count'),
        ),
    ]
