# Generated by Django 5.1.6 on 2025-03-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0019_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='discription',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
