# Generated by Django 5.1.6 on 2025-03-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0021_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
